targets:
  $default:
    builders:
      sass_builder:
        options:
          outputStyle: OutputStyle.compressed
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O4
            - -Ddebug=false
