name: Deploy gh-pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Generate code
        run: dart run build_runner build --release -o web:build

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # from https://github.com/kevmoo/peanut.dart/blob/75fe6ce2ad1f6b1927d9043c1308b12e3f57406d/lib/src/build_runner.dart#L112
          exclude_assets: '.github,./packages/intl/**,**.dart,**.dart.js.deps,**.dart.js.tar.gz,**.md,**.module,**.ng_placeholder,**.yaml,.build.manifest,.dart_tool/**,.packages,packages/$sdk/**,packages/analyzer/**,packages/build_runner/**,packages/build_web_compilers/**,packages/node_preamble/**,packages/package_resolver/**,packages/test/**'