name: Deploy gh-pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Generate code
        run: dart run build_runner build --release -o web:build

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Prepare cleanup of ./build
        uses: tj-actions/glob@v13
        id: glob
        # from https://github.com/kevmoo/peanut.dart/blob/75fe6ce2ad1f6b1927d9043c1308b12e3f57406d/lib/src/build_runner.dart#L112
        with:
          working-directory: ./build
          strip-top-level-dir: false
          match-directories: false
          escape-paths: true
          files: |
            ./packages/intl/**
            ./packages/_fe_analyzer_shared/**
            **.dart
            **.dart.js.deps
            **.dart.js.tar.gz
            **.md
            **.module
            **.ng_placeholder
            **.yaml
            .build.manifest
            .dart_tool/**
            .packages
            packages/$sdk/**
            packages/analyzer/**
            packages/build_runner/**
            packages/build_web_compilers/**
            packages/node_preamble/**
            packages/package_resolver/**
            packages/test/**

      - name: Cleanup ./build
        run: |
          rm ${{ steps.glob.outputs.paths }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
