name: Deploy gh-pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Generate code
        run: dart run build_runner build

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Activate peanut
        run: dart pub global activate peanut

      - name: Build gh-pages
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: peanut

      - name: Deploy to gh-pages
        uses: ad-m/github-push-action@9a46ba8d86d3171233e861a4351b1278a2805c83
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages